### ISSUE TITLE
GF Add-on workflow is not valid - Unexpected symbol: '['

### ISSUE THREAD

**Issue by vburlak** [sterner-stuff/private-wordpress-plugin-composer-provider#12]
Got such issue in Action while running a workflow for GF Add-on using latest changes related to #8 https://github.com/sterner-stuff/private-wordpress-plugin-composer-provider/commit/aff2cb81eab8bdc08a4a40f21a4409e8eb5475ae

> Invalid workflow file: .github/workflows/update.yml#L40
The workflow is not valid. .github/workflows/update.yml (Line: 40, Col: 14): Unexpected symbol: '['. Located at position 68 within expression: fromJson(steps.GravityFormsAPIResponse.outputs.response).offerings.[env.PACKAGE_SLUG].url_latest

**Comment by ethanclevenger91** [comment]
Fixed in ccd0741
